### ISSUE TITLE
Compatibilité univers étrangers

### ISSUE THREAD

**Issue by darknoon29** [OGSteam/mod-superapix#1]
Hello,

Je suis actuellement sur le serveur pioneers mais superapix ne connais que les unis fr.

Comment faire ?

Merci

**Comment by machine62** [comment]
Une mise à jour ?

**Comment by darknoon29** [comment]
Non nous avons je suis juste sur le ogame beta test en anglais 😊

**Comment by machine62** [comment]
cela se fait via la fonction : uni_replace()

elle change a la volée le numero et le pays d'un univers ayant pour chaine 
"https://s{uni}-{pays}.ogame.gameforge.com/api/universe.xml"

si le format n'est pas le même il faudra changer les constantes : include/cst.php l14 a 41
