### ISSUE TITLE
find_config() function not defined

### ISSUE THREAD

**Issue by kubealex** [OGSteam/mod-superapix#13]
Hi, after installing superapix 0.2.7 on a 3.3.4 ogspy, i get the following message when trying to retrieve info from the server:

FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function find_config() in /var/www/html/ogspy/mod/superapix/include/cst.php:52

It seems that the function find_config() is not defined anywhere.

Does superapix need any prerequisite to work?
Thanks

**Comment by darknoon29** [comment]
C'est de ma faute :-)

**Comment by darknoon29** [comment]
Corrigé avec ff4c726
