### ISSUE TITLE
une erreur est survenue [object Object]

### ISSUE THREAD

**Issue by mritou** [OGSteam/mod-superapix#16]
Bonjour,
Avec la version 0.2.7 fraichement DL, j'ai suivi le tutorial vidéo mais je me retrouve confronté à un pop up contenant le texte : une erreur est survenue [object Object]
La log apache :
PHP Fatal error:  Uncaught Error: Call to undefined function simplexml_load_file() in /var/www/html/ogspy/mod/superapix/include/function.php:138\nStack trace:\n#0 /var/www/html/ogspy/mod/superapix/cron.php(83): f_chargement_fichier_xml('mod/superapix/x...')\n#1 {main}\n  thrown in /var/www/html/ogspy/mod/superapix/include/function.php on line 138, referer:
Ce pop up apparait au moment ou je clic pour la première fois sur mise à jour
La version OGSpy est la 3.3.6 
La version php : PHP 7.3.7
Merci par avance pour votre aide.

**Comment by machine62** [comment]
Bonjour,

cela semble provenir de votre configuration PHP. Le module simple_XML ne semble pas activé. 
Si vous auto-hebergez sur du linux :
### apt-get install php7.0-simplexml 
[ a modifier selon la version de php cf doc officielle]

si vous êtes chez un hébergeur tierce, voir dans votre interface de gestion pour l'activer

bon courage

**Comment by mritou** [comment]
Bonjour,

Parfait, merci il manquait bien un package :)
Sur centos : yum install php-xml

Bonne journée et super boulot !
