### ISSUE TITLE
Callback Problem when Xtense not installed

### ISSUE THREAD

**Issue by darknoon29** [OGSteam/mod-superapix#18]
![image](https://user-images.githubusercontent.com/13015521/64681009-36647880-d47f-11e9-877b-fda92c87d8a8.png)

**Comment by darknoon29** [comment]
J'ai du mal à écrire les Bugs en Farnçais ^^

**Comment by machine62** [comment]
J'ai compris le pb quand même ...

depuis le temps que je parle des dépendances de mod :p 
on va finir par y venir
