### ISSUE TITLE
function.php on line 115

### ISSUE THREAD

**Issue by machine62** [OGSteam/mod-superapix#21]
@machine  Un log revient souvent sur superapix :

PHP message: PHP Warning:  A non-numeric value encountered in /srv/www/ogspy.fr/winners/mod/superapix/include/function.php on line 115
PHP message: PHP Warning:  A non-numeric value encountered in /srv/www/ogspy.fr/winners/mod/superapix/include/function.php on line 115
PHP message: PHP Warning:  A non-numeric value encountered in /srv/www/ogspy.fr/winners/mod/superapix/include/function.php on line 115
PHP message: PHP Warning:  A non-numeric value encountered in /srv/www/ogspy.fr/winners/mod/superapix/include/function.php on line 115
PHP message: PHP Warning:  A non-numeric value encountered in /srv/www/ogspy.fr/winners/mod/superapix/include/function.php on line 115
PHP message: PHP Warning:  A non-numeric value encountered in /srv/www/ogspy.fr/winners/mod/superapix/include/function.php on line 115
PHP message: PHP Warning:  A non-numeric value encountered in /srv/www/ogspy.fr/winners/mod/superapix/include/function.php on line 115
PHP message: PHP Warning:  A non-numeric value encountered in /srv/www/ogspy.fr/winners/mod/superapix/include/function.php on line 115
PHP message: PHP Warning:  A non-numeric value encountered in /srv/www/ogspy.fr/winners/mod/superapix/include/function.php on line 115
PHP message: PHP Warning:  A non-numeric value encountered in /srv/www/ogspy.fr/winners/mod/superapix/include/function.php on line 115

**Comment by darknoon29** [comment]
Version 0.3.0

**Comment by machine62** [comment]
Excuse moi, j'ai pris assez vite le bug sans véritablement verifier grand chsoe ..
De mémoire en dernière version c'est reglé

je le garde ouvert pour verif

**Comment by darknoon29** [comment]
Je Vai leur pousser la 0.3.3 alors si leur BDD le permet ☺️

**Comment by machine62** [comment]
clos
