### ISSUE TITLE
Compatibilité PHP 7.4.4

### ISSUE THREAD

**Issue by binu5975** [OGSteam/mod-superapix#23]
Bonjour, il semble y avoir un problème en utilisant PHP 7.4.4
J'ai beau cherché dans les lignes mentionnées dans les logs je ne vois rien à première vue
Lorsque je déclenche une mise à jour
J'obtiens le popup suivant : 
![image](https://user-images.githubusercontent.com/63189165/81233838-ddda8080-8ff7-11ea-9e7e-c35e5ed0044d.png)
Voici ce qu'indique le log Apache : 
PHP Fatal error:  Uncaught Error: Call to a member function sql_query() on null in C:\\xampp\\htdocs\\ogspy\\mod\\superapix\\model\\config.php:81\nStack trace:\n#0 C:\\xampp\\htdocs\\ogspy\\mod\\superapix\\common.php(47): defineDebug()\n#1 C:\\xampp\\htdocs\\ogspy\\mod\\superapix\\cron.php(19): include('C:\\\\xampp\\\\htdocs...')\n#2 {main}\n  thrown in C:\\xampp\\htdocs\\ogspy\\mod\\superapix\\model\\config.php on line 81

Et les requêtes SQL qui passent : 
SHOW TABLES LIKE "ogspy_xtense_callbacks"
SELECT active FROM ogspy_mod WHERE root = 'superapix'
select user_id from ogspy_user WHERE user_name = 'SPA_WebService'
SELECT config_value FROM ogspy_superapix_cfg WHERE config_name = 'uni'
SELECT config_value FROM ogspy_superapix_cfg WHERE config_name = 'requete_max'
SELECT config_value FROM ogspy_superapix_cfg WHERE config_name = 'pays'
SELECT id FROM ogspy_mod WHERE root = 'superapix'
SELECT config_value FROM ogspy_superapix_cfg WHERE config_name = 'last_CST_PLAYERS'
SELECT config_value FROM ogspy_superapix_cfg WHERE config_name = 'last_CST_ALLIANCES'
SELECT config_value FROM ogspy_superapix_cfg WHERE config_name = 'last_CST_ALLIANCES_RANK_POINTS'
SELECT config_value FROM ogspy_superapix_cfg WHERE config_name = 'last_CST_ALLIANCES_RANK_ECO'
SELECT config_value FROM ogspy_superapix_cfg WHERE config_name = 'last_CST_ALLIANCES_RANK_TECHNOLOGY'
SELECT config_value FROM ogspy_superapix_cfg WHERE confg_name = 'last_CST_ALLIANCES_RANK_MILITARY'
SELECT config_value FROM ogspy_superapix_cfg WHERE confiig_name = 'last_CST_ALLIANCES_RANK_MILITARY_BUILT'
SELECT config_value FROM ogspy_superapix_cfg WHERE config_name = 'last_CST_ALLIANCES_RANK_MILITARY_DESTROYED'
SELECT config_value FROM ogspy_superapix_cfg WHERE config_name = 'last_CST_ALLIANCES_RANK_MILITARY_LOST'
SELECT config_value FROM ogspy_superapix_cfg WHERE config_name = 'last_CST_ALLIANCES_RANK_MILITARY_HONNOR'
SELECT config_value FROM ogspy_superapix_cfg WHERE config_name = 'last_CST_PLAYERS_RANK_POINTS'
SELECT config_value FROM ogspy_superapix_cfg WHERE config_name = 'last_CST_PLAYERS_RANK_ECO'
SELECT config_value FROM ogspy_superapix_cfg WHERE config_name = 'last_CST_PLAYERS_RANK_TECHNOLOGY'
SELECT config_value FROM ogspy_superapix_cfg WHERE config_name = 'last_CST_PLAYERS_RANK_MILITARY'
SELECT config_value FROM ogspy_superapix_cfg WHERE config_name = 'last_CST_PLAYERS_RANK_MILITARY_BUILT'
SELECT config_value FROM ogspy_superapix_cfg WHERE config_name = 'last_CST_PLAYERS_RANK_MILITARY_DESTROYED'
SELECT config_value FROM ogspy_superapix_cfg WHERE config_name = 'last_CST_PLAYERS_RANK_MILITARY_LOST'
SELECT config_value FROM ogspy_superapix_cfg WHERE config_name = 'last_CST_PLAYERS_RANK_MILITARY_HONNOR'
SELECT config_value FROM ogspy_superapix_cfg WHERE config_name = 'last_CST_UNIVERSE'
SELECT `user_id` FROM ogspy_user WHERE `user_active` = '1'

Merci

**Comment by machine62** [comment]
Merci du retour, il faut que j'upgrade mon environnement ...
je suis en 7.2 de memoire :s

**Comment by machine62** [comment]
Superpaix foncionne sous php 7.4.5

```
11/05/2020 06:52:08 : [superapix] SPA_WebService retour {"ok":"Injection CST_UNIVERSE","temps":3.951223850250244,"CPU":null,"memory":"2.31 mb \/ 8.41 mb","State":"AtWork"}
11/05/2020 06:52:08 : [superapix] SPA_WebService Usage memoire : 2.31 mb / 8.41 mb [fin script CST_UNIVERSE]
11/05/2020 06:52:08 : [superapix] SPA_WebService Usage memoire : 2.31 mb / 8.41 mb [fin traitement_universe]
11/05/2020 06:52:05 : [superapix] SPA_WebService Traitement fichier XML
11/05/2020 06:52:05 : [superapix] SPA_WebService Usage memoire : 2.33 mb / 2.44 mb [Fin chargement XML mod/superapix/xml/CST_UNIVERSE.xml]
11/05/2020 06:52:04 : [superapix] SPA_WebService Usage memoire : 2.33 mb / 2.44 mb [chargement XML mod/superapix/xml/CST_UNIVERSE.xml]
11/05/2020 06:52:04 : [superapix] SPA_WebService link fichier XMLmod/superapix/xml/CST_UNIVERSE.xml
11/05/2020 06:52:04 : [superapix] SPA_WebService Chargement fichier XML
11/05/2020 06:52:04 : [superapix] SPA_WebService xml CST_UNIVERSE est ok, Injection BDD
```

**Comment by binu5975** [comment]
J'ai mis à jour en php 7.4.5
Même souci
J'ai fait une nouvelle install sur un xampp vide même souci
Peut-être une question d'os ou une extension php à activer?

**Comment by darknoon29** [comment]
@binu5975 Tu peux essayer avec la dernière version ? Merci :-)
