### ISSUE TITLE
Cron.php not working

### ISSUE THREAD

**Issue by Hari-Seld0n** [OGSteam/mod-superapix#32]
![image](https://github.com/OGSteam/mod-superapix/assets/133211480/e2cd6455-6f04-4249-83d8-7af14345d65e)

Lors de la mise à jour des données, l'appel de /superapix/cron.php renvoie une erreur 500

**Comment by machine62** [comment]
Le fichier xml ne semble pas present.

Pour info,  via l'interface ogspy cela fonctionne.

si oui, mettre en relation avec : https://github.com/OGSteam/mod-superapix/issues/31

**Comment by Hari-Seld0n** [comment]
J'exécute bien le script depuis l'interface OGspy :
![image](https://github.com/OGSteam/mod-superapix/assets/133211480/9115ebfa-8fbd-455b-9e2b-2ea00c5c4047)

Le mod est en version 
![image](https://github.com/OGSteam/mod-superapix/assets/133211480/187b6cf1-cdba-4961-bd7c-73a7f9264a17)

**Comment by machine62** [comment]
Test sur plusieurs ogspy dev/prod
pas de reproduction d erreur.
