### ISSUE TITLE
Maj via API impossible

### ISSUE THREAD

**Issue by ElijahFR** [OGSteam/mod-superapix#4]
Bonjour Machine,
La mise à jour via API ne se fait pas malgré une bonne configuration du mods (je l'ai jamais touché, ça marchait avant que ça passe en API).
Déjà désinstallé et réinstallé.
![2](https://user-images.githubusercontent.com/32208232/30764350-c5b627a2-9fea-11e7-8ec2-7a366ec93d7a.PNG)
![3](https://user-images.githubusercontent.com/32208232/30764352-c5f3613a-9fea-11e7-8162-fcc9177b8df8.PNG)

**Comment by machine62** [comment]
Je prends ...

**Comment by machine62** [comment]
je viens de tester tout est ok de mon coté ( test sur univers vide ... )

1) active le mode debug
2) ajoute les callback xtense

y a t'il des modifications ? et sinon peut on avoir une exort du journal ogspy ?

**Comment by darknoon29** [comment]
Peut-être juste un soucis de documentation pour la 1ère utilisation ;-)

**Comment by machine62** [comment]
Pour une premiere utilisation 
1) je clique sur "remplir univers"
2) il s'agit d une sorte de web service il faut donc appeler la page suivante : https://nomogspy/mod/superapix/cron.php

je vais prochainement remettre l'interface visuelle pour injecter via js ....

**Comment by machine62** [comment]
https://github.com/OGSteam/mod-superapix/tree/0.2.2
