### ISSUE TITLE
Erreur Mise à jour des données PHP 7.2

### ISSUE THREAD

**Issue by darknoon29** [OGSteam/mod-superapix#8]
Lors de l'utilisation de Superapix avec PHP 7.2 une erreur apparait dans la gestion des données:

A non well formed numeric value encountered in <b>D:\UwAmp\www\ogspy\mod\superapix\include\function.php</b> on line <b>257</b><br />

![2018-08-11](https://user-images.githubusercontent.com/13015521/43991526-f8ae2e70-9d6e-11e8-8087-e58731972fb3.png)

**Comment by machine62** [comment]
je down la version 7.2 sous uwamp et je corrige

**Comment by machine62** [comment]
66608f7f4b35d9a2c258f30f6c535e9f63aef8f5
